typedef User = ({String username});

typedef Message = ({String id, String content, User sender, DateTime timestamp});

typedef Conversation = ({String id, String name, List<Message> messages});

class MockData {
  MockData._();

  static final User users1 = (username: 'User 1');
  static final User users2 = (username: 'User 2');
  static final User users3 = (username: 'User 3');

  static final List<Message> conv1Messages = [
    (id: 'msg1', content: 'Hey, how are you?', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 1))),
    (id: 'msg3', content: 'Doing well, just working on a project.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 2))),
    (id: 'msg2', content: 'I\'m good, thanks! How about you?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 3))),
    (id: 'msg4', content: 'Oh nice, what kind of project?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 4))),
    (id: 'msg5', content: 'It\'s a Flutter app.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 5))),
    (id: 'msg6', content: 'Cool! Flutter is awesome.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 6))),
    (id: 'msg7', content: 'Yeah, hot reload makes life easier.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 7))),
    (id: 'msg8', content: 'Exactly!', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 8))),
    (id: 'msg9', content: 'Are you using it for work or a side project?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 9))),
    (id: 'msg10', content: 'Work. It’s a chat app for a client.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 10))),
    (id: 'msg11', content: 'Oh nice, are you building real-time messaging?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 11))),
    (id: 'msg12', content: 'Yep, using Firebase for that.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 12))),
    (id: 'msg13', content: 'Good choice.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 13))),
    (id: 'msg14', content: 'I use it all the time too.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 14))),
    (id: 'msg15', content: 'Same, it saves so much time.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 15))),
    (id: 'msg16', content: 'Do you like Riverpod?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 16))),
    (id: 'msg17', content: 'Yes! Much cleaner than Provider.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 17))),
    (id: 'msg18', content: 'Agreed.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 18))),
    (id: 'msg19', content: 'What’s the hardest part so far?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 19))),
    (id: 'msg20', content: 'Probably syncing messages across devices.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 20))),
    (id: 'msg21', content: 'Yeah, I struggled with that too.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 21))),
    (id: 'msg22', content: 'Firestore makes it easier though.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 22))),
    (id: 'msg23', content: 'True.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 23))),
    (id: 'msg24', content: 'Have you added authentication yet?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 24))),
    (id: 'msg25', content: 'Yes, Firebase Auth with Google login.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 25))),
    (id: 'msg26', content: 'Perfect.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 26))),
    (id: 'msg27', content: 'Dark mode is also in.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 27))),
    (id: 'msg28', content: 'Nice!', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 28))),
    (id: 'msg29', content: 'I personally only use dark mode.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 29))),
    (id: 'msg30', content: 'Same 😅', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 30))),
    (id: 'msg31', content: 'Have you thought about group chats?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 31))),
    (id: 'msg32', content: 'Yes, planning to add them after beta.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 32))),
    (id: 'msg33', content: 'That’ll be awesome.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 33))),
    (id: 'msg34', content: 'By the way, media sharing is already in.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 34))),
    (id: 'msg35', content: 'No way, that’s great!', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 35))),
    (id: 'msg36', content: 'Yep, images and files supported.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 36))),
    (id: 'msg37', content: 'You’re way ahead!', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 37))),
    (id: 'msg38', content: 'Haha not really, still polishing UI.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 38))),
    (id: 'msg39', content: 'Send me a screenshot later.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 39))),
    (id: 'msg40', content: 'Sure!', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 40))),
    (id: 'msg41', content: 'Just pushed some changes.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 41))),
    (id: 'msg42', content: 'Cool, I’ll pull and check.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 42))),
    (id: 'msg43', content: 'Thanks!', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 43))),
    (id: 'msg44', content: 'What branch?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 44))),
    (id: 'msg45', content: 'feature/chat-ui', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 45))),
    (id: 'msg46', content: 'Got it.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 46))),
    (id: 'msg47', content: 'UI looks clean btw.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 47))),
    (id: 'msg48', content: 'Appreciate it 🙌', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 48))),
    (id: 'msg49', content: 'Any bugs?', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 49))),
    (id: 'msg50', content: 'Scroll is a bit jittery on Android.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 50))),
    (id: 'msg51', content: 'Ah, I’ll profile it later.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 51))),
    (id: 'msg52', content: 'Maybe use ListView.builder.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 52))),
    (id: 'msg53', content: 'Already using it 😅', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 53))),
    (id: 'msg54', content: 'Haha okay then.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 54))),
    (id: 'msg55', content: 'I’ll try caching avatars.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 55))),
    (id: 'msg56', content: 'Smart.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 56))),
    (id: 'msg57', content: 'Do you use shimmer loading?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 57))),
    (id: 'msg58', content: 'Yes, added last night.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 58))),
    (id: 'msg59', content: 'Nice touch.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 59))),
    (id: 'msg60', content: 'Thinking of adding typing indicators.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 60))),
    (id: 'msg61', content: 'That’d be sick.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 61))),
    (id: 'msg62', content: 'Also read receipts.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 62))),
    (id: 'msg63', content: 'Double ticks? 😆', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 63))),
    (id: 'msg64', content: 'Exactly.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 64))),
    (id: 'msg65', content: 'Love it.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 65))),
    (id: 'msg66', content: 'By the way, added push notifications.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 66))),
    (id: 'msg67', content: 'Wow, that was fast!', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 67))),
    (id: 'msg68', content: 'Expo made it easy.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 68))),
    (id: 'msg69', content: 'Cool, I need to learn that.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 69))),
    (id: 'msg70', content: 'I can show you later.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 70))),
    (id: 'msg71', content: 'Please do.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 71))),
    (id: 'msg72', content: 'Also added emoji picker 😁', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 72))),
    (id: 'msg73', content: 'Brooo that’s awesome.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 73))),
    (id: 'msg74', content: 'Yep, uses a package.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 74))),
    (id: 'msg75', content: 'Which one?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 75))),
    (id: 'msg76', content: 'emoji_picker_flutter.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 76))),
    (id: 'msg77', content: 'Nice.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 77))),
    (id: 'msg78', content: 'Works well.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 78))),
    (id: 'msg79', content: 'Let’s test media upload today.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 79))),
    (id: 'msg80', content: 'Sure thing.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 80))),
    (id: 'msg81', content: 'Uploaded a 5MB image, worked.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 81))),
    (id: 'msg82', content: 'Good to know.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 82))),
    (id: 'msg83', content: 'Video still pending.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 83))),
    (id: 'msg84', content: 'Yeah, need to compress first.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 84))),
    (id: 'msg85', content: 'Makes sense.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 85))),
    (id: 'msg86', content: 'Did you push the fix for auth redirect?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 86))),
    (id: 'msg87', content: 'Yep, this morning.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 87))),
    (id: 'msg88', content: 'Good stuff.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 88))),
    (id: 'msg89', content: 'Might add Apple login later.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 89))),
    (id: 'msg90', content: 'That’s a requirement for iOS store.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 90))),
    (id: 'msg91', content: 'Exactly.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 91))),
    (id: 'msg92', content: 'Good thinking ahead.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 92))),
    (id: 'msg93', content: 'Thanks!', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 93))),
    (id: 'msg94', content: 'How about theming?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 94))),
    (id: 'msg95', content: 'Supports system theme.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 95))),
    (id: 'msg96', content: 'Nice and modern.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 96))),
    (id: 'msg97', content: 'Also added message reactions.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 97))),
    (id: 'msg98', content: 'Like 👍 and ❤️?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 98))),
    (id: 'msg99', content: 'Yep!', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 99))),
    (id: 'msg100', content: 'This is turning into WhatsApp lol.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 100))),
    (id: 'msg101', content: 'Haha yeah pretty much.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 101))),
    (id: 'msg102', content: 'Not a bad thing tho.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 102))),
    (id: 'msg103', content: 'True.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 103))),
    (id: 'msg104', content: 'I’ll try to stress test it later.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 104))),
    (id: 'msg105', content: 'Good idea.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 105))),
    (id: 'msg106', content: 'Maybe with 1000 dummy users.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 106))),
    (id: 'msg107', content: 'Oh wow 😅', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 107))),
    (id: 'msg108', content: 'We’ll see how Firebase handles it.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 108))),
    (id: 'msg109', content: 'Probably fine.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 109))),
    (id: 'msg110', content: 'Agreed.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 110))),
    (id: 'msg111', content: 'I’ll add some loading tests.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 111))),
    (id: 'msg112', content: 'Cool.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 112))),
    (id: 'msg113', content: 'Oh btw, fixed the keyboard issue on iOS.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 113))),
    (id: 'msg114', content: 'Sweet, that was annoying.', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 114))),
    (id: 'msg115', content: 'Agreed.', sender: users1, timestamp: DateTime.now().subtract(Duration(minutes: 115))),
    (id: 'msg116', content: 'Did you test on iPad?', sender: users2, timestamp: DateTime.now().subtract(Duration(minutes: 116))),
  ];
}
